   import java.awt.image.BufferedImage;
   import java.io.IOException;
   import javax.imageio.ImageIO;
   import javax.swing.JOptionPane;
   import java.io.*;
   import java.util.*;

/**
 * 
 * @author Allen - Also messed with by Chris
 *
 */
   public class ImageSlicer {
      BufferedImage img;
      String[] fileInfo;
   
      public ImageSlicer(BufferedImage i, String filename){
         img = i;
         fileInfo = filename.split("\\.");
      }
   
   /**
    * Breaks the given image up and saves the sub images to the user's desktop.
    * @param width Width of Subimages
    * @param height Height of Subimages
    */
      public void slice(int width, int height){		
         int x = img.getWidth()/width;
         int y = img.getHeight()/height;
      
         if(x == 0 && y == 0){
            infoBox("SubImages are larger than original!", "Error");
            System.exit(2);
         }
         if (img.getWidth()%width > 0){
            ++x;
         }
         if (img.getHeight()%height > 0){
            ++y;
         }
      	
         int count = 1;    
      
         BufferedImage[][] images = new BufferedImage[x][y];
         File outputfile = null;
         for (int j = 0; j < y; ++j){
            for (int i = 0; i < x; ++i){
               int w = width;
               int h = height;
               if (i+1 == x && img.getWidth()%width != 0){
                  w = img.getWidth()%width;					
               }
               if (j+1 == y && img.getHeight()%height != 0){
                  h = img.getHeight()%height;			
               }
            
               images[i][j] = img.getSubimage(i*width,j*height, w, h);
            
               try {		
               //This will save to where the JAR is saved, in the folder "output".
                  String stupidlongthing = ClassLoader.getSystemClassLoader().getResource(".").getPath().replaceAll("%20", " ")+"\\output\\sprites\\images\\spr_"+fileInfo[0]+"_"+i+"_"+j+"."+fileInfo[fileInfo.length-1];
                  stupidlongthing = stupidlongthing.replaceAll("file:/", "").replaceAll("ImageBreaker.jar\\!", "");      
               	
                  outputfile = new File(stupidlongthing);
               
                  System.out.println(count+"/"+(x*y));
                  count++;
                  File directory = outputfile.getParentFile();
                  directory.mkdirs();
                  
                  ImageIO.write(images[i][j], fileInfo[fileInfo.length-1], outputfile);//Returns true if save succesful			    
               	
               } 
                  catch (IOException e) {
                     //infoBox("Save failed!", "Error");
                  }
            		
            		//sprite.gmx files!?
               try {
                  BufferedWriter out = new BufferedWriter(new FileWriter("output\\sprites\\obj_"+fileInfo[0]+"_"+i+"_"+j+".sprite.gmx"));
                  out.write("<!--This Document is generated by GameMaker, if you edit it by hand then you do so at your own risk!-->"); out.newLine();
                  out.write("<sprite>"); out.newLine();
                  out.write("  <xorig>0</xorig>"); out.newLine();
                  out.write("  <yorigin>0</yorigin>"); out.newLine();
                  out.write("  <colkind>0</colkind>"); out.newLine();
                  out.write("  <coltolerance>0</coltolerance>"); out.newLine();
                  out.write("  <sepmasks>-1</sepmasks>"); out.newLine();
                  out.write("  <bboxmode>0</bboxmode>"); out.newLine();
                  out.write("  <bbox_left>0</bbox_left>"); out.newLine();
                  out.write("  <bbox_right>1023</bbox_right>"); out.newLine();
                  out.write("  <bbox_top>0</bbox_top>"); out.newLine();
                  out.write("  <bbox_bottom>1023</bbox_bottom>"); out.newLine();
                  out.write("  <HTile>0</HTile>"); out.newLine();
                  out.write("  <VTile>0</VTile>"); out.newLine();
                  out.write("  <TextureGroup>0</TextureGroup>"); out.newLine();
                  out.write("  <For3D>0</For3D>"); out.newLine();
                  out.write("  <frames>"); out.newLine();
                  out.write("    <frame index=\"0\">images\\spr_"+fileInfo[0]+"_"+i+"_"+j+"."+fileInfo[fileInfo.length-1]+"</frame>"); out.newLine();
                  out.write("  </frames>"); out.newLine();
                  out.write("</sprite>"); out.newLine();
               	
                  out.close();
               }
                  catch (IOException e)
                  {
                     System.out.println("Exception ");       
                  }
            }
         }
         
         System.out.println("Saving completed.");
      }
   
      private void infoBox(String infoMessage, String title)
      {
         JOptionPane.showMessageDialog(null, infoMessage, title, JOptionPane.INFORMATION_MESSAGE);
      }
   }
